
stages:
  - build and push
  - deploy

.default_tags: &default_tags
  tags:
    - 10-runner

.build_variables: &build_variables
  DOCKER_FILE_API: "game-x.api/Dockerfile"

# 共用 Build Script
.build_script: &build_script
  - apk add --no-cache git openssh-client
  - echo "$HARBOR_PASSWORD" | docker login $HARBOR_REGISTRY -u $HARBOR_USERNAME --password-stdin
  - CI_IMAGE_API=$HARBOR_REGISTRY/$PROJECT_NAME_API:$TAG_NAME
  - docker build -t $CI_IMAGE_API -f $DOCKER_FILE_API .
  - docker push $CI_IMAGE_API

# 共用 Deploy Script
.deploy_before_script: &deploy_before_script
  - eval $(ssh-agent -s)
  - echo "$GITLAB_RUNNER_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -p $SSH_PORT $SERVER >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

.deploy_script: &deploy_script
  # 設定環境變數
  - echo "部署專案開始..."
  - CI_IMAGE_API=$HARBOR_REGISTRY/$PROJECT_NAME_API:$TAG_NAME
 
    # SSH 連接
  - |
    echo "ssh 連接"  
    ssh -p $SSH_PORT "$DEPLOY_HOST@$SERVER" "sudo -u dls /home/dls/gamex/deploy_gamex.sh $CI_IMAGE_API $HARBOR_REGISTRY $HARBOR_USERNAME '$HARBOR_PASSWORD'"

# =====================================
# ✅ 各環境部署區塊
# =====================================
# Docker Build + Push
dev_docker_build:
  stage: build and push
  image: docker
  <<: *default_tags
  variables:
    <<: *build_variables
    PROJECT_NAME_API: gamex/api-dev
    TAG_NAME: develop
  script:
    - *build_script
  only:
    - develop
 
deploy_dev:
  stage: deploy
  <<: *default_tags
  variables:
    SERVER: $DEV_SERVER
    SSH_PORT: $DEV_SSH_PORT
    DEPLOY_HOST: deploy
    ENVIRONMENT: dev
    TAG_NAME: develop
    PROJECT_NAME_API: gamex/api-dev
  before_script: *deploy_before_script
  script:
    - *deploy_script
  only:
    - develop

