version: "3.8"

services:
  gamex_pg:
    image: postgres:15
    container_name: gamex_pg
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - gamex-pg

  game-x.api:
    image: ${DOCKER_REGISTRY-}gamexapi
    container_name: game-x.api
    build:
      context: .
      dockerfile: game-x.api/Dockerfile
    networks:
      - gamex-pg
    depends_on:
      - gamex_pg
    ports:
      - 5111:8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=gamex_pg;Port=5432;User Id=postgres;Password=postgres;Database=gamex;SSLMode=Disable;Trust Server Certificate=true;
      - ConnectionStrings__HangfireConnection=Server=gamex_pg;Port=5432;User Id=postgres;Password=postgres;Database=hangfire;SSLMode=Disable;Trust Server Certificate=true;
      - API_PORT=${API_PORT}
      - HANGFIRE_KEY=${HANGFIRE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_PROVIDER=${JWT_PROVIDER}
      - JWT_VERSION=${JWT_VERSION}
      - JWT_EXPIRED_MINUTES=${JWT_EXPIRED_MINUTES}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - UXM_HOST=${UXM_HOST}
      - GALAXY_MERCHANTNUMBER=${GALAXY_MERCHANTNUMBER}
      - EngageLab_BaseUrl=${EngageLab_BaseUrl}
      - EngageLab_ApiUser=${EngageLab_ApiUser}
      - EngageLab_ApiKey=${EngageLab_ApiKey}
      - EngageLab_From=${EngageLab_From}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - RecurringJob_DashboardStatisticJob=${RecurringJob_DashboardStatisticJob}
      - RecurringJob_SessionCleanUpJob=${RecurringJob_SessionCleanUpJob}

networks:
  gamex-pg:
    driver: bridge
