services:
  gamex.db:
    image: postgres:16.4

  gamex.api:
    image: game-x.api
    build:
      context: .
      dockerfile: game-x.api/Dockerfile

  gamex.seq:
    image: datalust/seq:latest

  gamex.srs:
    image: ossrs/srs:5

networks:
  dls-gamex:
    external: true

volumes:
  game-x-seq-data:
  srs_data:
  postgres_gamex:
