services:
  db:
    image: postgres:16.4

  api:
    image: game-x.api
    build:
      context: .
      dockerfile: game-x.api/Dockerfile

  seq:
    image: datalust/seq:latest

  srs:
    image: ossrs/srs:5

networks:
  dls-gamex:
    external: true

volumes:
  seq-data:
  srs-data:
  db-data:
