namespace game_x.application.Features.Chat.Dtos;

public sealed record ConversationDetailDto(
    Guid ConversationId,
    string? GuestId,
    ConversationStatus Status,
    ConversationType Type,
    RoleInConversation? LastSenderRole,
    string? CustomerId,
    string? CustomerDisplayName,
    string? CustomerAvatarUrl,
    DateTime? LastResolvedAt,
    int? LastResolvedMessageId,
    DateTime? LastGuestReadAt,
    int? LastGuestReadMessageId,
    DateTime? LastUserReadAt,
    int? LastUserReadMessageId,
    string LastUserId,
    string LastUserName,
    string? LastUserAvatarUrl,
    DateTime LastMessageAt,
    Guid LastMessageId,
    string LastMessageText,
    MessageKind LastMessageKind,
    bool? IsHidden,
    int? UnreadCount);