namespace game_x.share.ExternalApi.Uxm.Dtos;

public record UxmOrderDetailInfoResponse(
    string? MerchantNumber,
    string? TradeNo,
    string? RedirectUrl,
    int CryptoType,
    string? CryptoTypeDesc,
    decimal CryptoAmount,
    int FiatType,
    string? FiatTypeDesc,
    decimal FiatAmount,
    int Type,
    string? TypeDesc,
    int Status,
    string? StatusDesc,
    int DisputeStatus,
    string? DisputeStatusDesc,
    string? PayerBankAccountName,
    string? PayeeBankName,
    string? PayeeBranchCode,
    string? PayeeName,
    string? PayeeAccountNumber,
    string? UserPaidAt,
    string? CompletedAt,
    string? CreatedAt);
